"""initial schema

Revision ID: d480bca0e623
Revises: 
Create Date: 2026-04-16 23:01:41.035837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd480bca0e623'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('platform_role', sa.Enum('PLATFORM_ADMIN', 'USER', name='platformrole'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('discoverable', sa.Boolean(), nullable=False),
    sa.Column('total_doors_knocked', sa.Integer(), nullable=False),
    sa.Column('total_contacts_made', sa.Integer(), nullable=False),
    sa.Column('total_campaigns', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('voters',
    sa.Column('state_voter_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('party', sa.String(length=20), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('voter_status', sa.String(length=20), nullable=False),
    sa.Column('congressional_district', sa.String(length=20), nullable=True),
    sa.Column('state_senate_district', sa.String(length=20), nullable=True),
    sa.Column('state_house_district', sa.String(length=20), nullable=True),
    sa.Column('county_council_district', sa.String(length=20), nullable=True),
    sa.Column('school_district', sa.String(length=100), nullable=True),
    sa.Column('precinct', sa.String(length=50), nullable=True),
    sa.Column('vote_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('modeled_ethnicity', sa.String(length=50), nullable=True),
    sa.Column('modeled_income', sa.String(length=50), nullable=True),
    sa.Column('modeled_education', sa.String(length=50), nullable=True),
    sa.Column('turnout_score', sa.Float(), nullable=True),
    sa.Column('partisanship_score', sa.Float(), nullable=True),
    sa.Column('persuadability_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 auto-creates idx_voters_location GIST index during CREATE TABLE
    op.create_index(op.f('ix_voters_last_name'), 'voters', ['last_name'], unique=False)
    op.create_index('ix_voters_name_dob', 'voters', ['last_name', 'first_name', 'date_of_birth'], unique=False)
    op.create_index(op.f('ix_voters_party'), 'voters', ['party'], unique=False)
    op.create_index(op.f('ix_voters_precinct'), 'voters', ['precinct'], unique=False)
    op.create_index(op.f('ix_voters_state'), 'voters', ['state'], unique=False)
    op.create_index(op.f('ix_voters_state_house_district'), 'voters', ['state_house_district'], unique=False)
    op.create_index('ix_voters_state_voter_id', 'voters', ['state', 'state_voter_id'], unique=True)
    op.create_index(op.f('ix_voters_zip_code'), 'voters', ['zip_code'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('campaign_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CAMPAIGN_ADMIN', 'ORGANIZER', 'VOLUNTEER', name='campaignrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('doors_knocked', sa.Integer(), nullable=False),
    sa.Column('contacts_made', sa.Integer(), nullable=False),
    sa.Column('hours_volunteered', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_voters',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('in_target_universe', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('support_level', sa.String(length=20), nullable=True),
    sa.Column('volunteer_prospect', sa.Boolean(), nullable=False),
    sa.Column('yard_sign_request', sa.Boolean(), nullable=False),
    sa.Column('vote_by_mail_interest', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_voters_campaign_voter', 'campaign_voters', ['campaign_id', 'voter_id'], unique=True)
    op.create_table('precinct_notes',
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('precinct', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turfs',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('total_doors', sa.Integer(), nullable=False),
    sa.Column('doors_knocked', sa.Integer(), nullable=False),
    sa.Column('contacts_made', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 auto-creates idx_turfs_boundary GIST index during CREATE TABLE
    op.create_table('volunteer_contacts',
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('contacted', sa.Boolean(), nullable=False),
    sa.Column('contact_result', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_results',
    sa.Column('campaign_voter_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('turf_id', sa.UUID(), nullable=True),
    sa.Column('contact_method', sa.Enum('DOOR_KNOCK', 'PHONE', 'TEXT', 'RELATIONAL', name='contactmethod'), nullable=False),
    sa.Column('disposition', sa.Enum('CONTACT', 'NOT_HOME', 'REFUSED', 'MOVED', 'DECEASED', 'INACCESSIBLE', 'COME_BACK', 'LANGUAGE_BARRIER', 'HOSTILE', 'WRONG_NUMBER', 'VOICEMAIL', 'NO_ANSWER', name='disposition'), nullable=False),
    sa.Column('survey_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_level', sa.String(length=20), nullable=True),
    sa.Column('volunteer_prospect', sa.Boolean(), nullable=False),
    sa.Column('yard_sign_request', sa.Boolean(), nullable=False),
    sa.Column('vote_by_mail_interest', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_voter_id'], ['campaign_voters.id'], ),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_results_campaign_voter', 'contact_results', ['campaign_voter_id'], unique=False)
    op.create_index('ix_contact_results_contacted_at', 'contact_results', ['contacted_at'], unique=False)
    op.create_index('ix_contact_results_volunteer', 'contact_results', ['volunteer_id'], unique=False)
    op.create_table('survey_questions',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_key', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turf_voters',
    sa.Column('turf_id', sa.UUID(), nullable=False),
    sa.Column('campaign_voter_id', sa.UUID(), nullable=False),
    sa.Column('walk_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_voter_id'], ['campaign_voters.id'], ),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turf_voters')
    op.drop_table('survey_questions')
    op.drop_index('ix_contact_results_volunteer', table_name='contact_results')
    op.drop_index('ix_contact_results_contacted_at', table_name='contact_results')
    op.drop_index('ix_contact_results_campaign_voter', table_name='contact_results')
    op.drop_table('contact_results')
    op.drop_table('volunteer_contacts')
    op.drop_index('idx_turfs_boundary', table_name='turfs', postgresql_using='gist')
    op.drop_table('turfs')
    op.drop_table('surveys')
    op.drop_table('precinct_notes')
    op.drop_index('ix_campaign_voters_campaign_voter', table_name='campaign_voters')
    op.drop_table('campaign_voters')
    op.drop_table('campaign_members')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_voters_zip_code'), table_name='voters')
    op.drop_index('ix_voters_state_voter_id', table_name='voters')
    op.drop_index(op.f('ix_voters_state_house_district'), table_name='voters')
    op.drop_index(op.f('ix_voters_state'), table_name='voters')
    op.drop_index(op.f('ix_voters_precinct'), table_name='voters')
    op.drop_index(op.f('ix_voters_party'), table_name='voters')
    op.drop_index('ix_voters_name_dob', table_name='voters')
    op.drop_index(op.f('ix_voters_last_name'), table_name='voters')
    op.drop_index('idx_voters_location', table_name='voters', postgresql_using='gist')
    op.drop_table('voters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
